# Generated by Django 2.2.5 on 2019-10-31 20:00

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='country',
            field=django_countries.fields.CountryField(default='', max_length=2),
        ),
    ]
