# Generated by Django 2.2.5 on 2019-10-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='instant_book',
            field=models.BooleanField(default=False),
        ),
    ]
